spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 
            clientSecret: 
          github:
            clientId: 
            clientSecret: 
          facebook:
            clientId: 
            clientSecret: 
